### ISSUE TITLE
Acept multiple clients from server

### ISSUE THREAD

**Issue by KSExtrez** [KSExtrez/Imgeneus#5]
## Description
The `Server` should accept incoming clients and add them to the internal dictionary of clients (`IDictionary<Guid, IClient>`), we should be use [SocketAsyncEventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketasynceventargs?view=netframework-4.8).

## Roadmap

- [x] Accept clients clients with `ServerAcceptor` class (https://github.com/KSExtrez/Imgeneus/commit/179d1509148189343206c2194d257463a4b2b29a)
- [x] Create new `ServerClient`
- [x] Add clients to internal dictionary (https://github.com/KSExtrez/Imgeneus/commit/25d5697412f93866f362fa74acac4acfd16ddf11)
