### ISSUE TITLE
Send packets to multiple clients

### ISSUE THREAD

**Issue by KSExtrez** [KSExtrez/Imgeneus#6]
## Description
The `Server` should start receiving data after the client has been accepted by the `ServerAcceptor`.
We will to have 3 methods:

-  Send a packet to one connected clients.
-  Send a packet to a collection of connected clients.
-  Send a packet to all connected clients.

## Roadmap

- [x] Server can send packets to one or more clients. (https://github.com/KSExtrez/Imgeneus/commit/498673a3d6b476d9667303f57e59e5517a440361)
- [x] The `Client` can send packet to other connected clients
- [x] Process sending queue (https://github.com/KSExtrez/Imgeneus/commit/498673a3d6b476d9667303f57e59e5517a440361)
