### ISSUE TITLE
Receive data from clients

### ISSUE THREAD

**Issue by KSExtrez** [KSExtrez/Imgeneus#7]
## Description
The `Server` should start receiving data after the client has been accepted by the `ServerAcceptor`.

## Roadmap

- [x] Start receiving data
- [x]   Handle packed data
- [x]   Call correct client data handler
