### ISSUE TITLE
Create Imgeneus.Client

### ISSUE THREAD

**Issue by KSExtrez** [KSExtrez/Imgeneus#8]
## Description
The `Imgeneus.Client` is a TCP client. It provides the possibility to connect to a `Imgeneus.Server` or any other kind of TCP servers, send and receive packets.

## Roadmap

- [ ] Create the `ClientConfiguration` class
- [ ] Connect to `Server`
- [ ] Send packets
- [ ] Receive packets
- [ ] Disconnects from a server
- [ ] Retry connection when connection is lost
