### ISSUE TITLE
Login Server

### ISSUE THREAD

**Issue by KSExtrez** [KSExtrez/Imgeneus#9]
## Description
The `Imgeneus.Login` should be having an internal Dictionary of connected `Imgeneus.World` and then use this info in the user login request.

## Roadmap (Client - Server)

- [ ] Send and Receive [Login Handshake](https://github.com/KSExtrez/Imgeneus/blob/master/docs/packets/LOGIN.md#login_handshake-0xa101) Request
- [ ] Process [Login Request](https://github.com/KSExtrez/Imgeneus/blob/master/docs/packets/LOGIN.md#login_request-0xa102)
- [ ] Check if user is already login
- [ ] Disconnect the current client if user is already login
- [ ] If the client is successfully logged, then send a [Server List](https://github.com/KSExtrez/Imgeneus/blob/master/docs/packets/LOGIN.md#server_list-0xa201)
- [ ] Process Select Server request
- [ ] If client version it's different than server version, send error

## Roadmap (Internal Server)

- [ ] Add new `Imgeneus.World` Server to `Imgeneus.Login` Server
- [ ] Add `Imgeneus.World` to internal Dictionary of connected Worlds `IDictionary<Guid, Imgeneus.World>`
- [ ] When a client its success full server selected, then send user and identity keys to `Imgeneus.World`
